/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthenticationForm: typeof import('./components/AuthenticationForm.vue')['default']
    Authority: typeof import('./components/Authority.vue')['default']
    AvatarWithError: typeof import('./components/AvatarWithError.vue')['default']
    Buffer: typeof import('./components/charts/Buffer.vue')['default']
    CaptchaInput: typeof import('./components/forms/CaptchaInput.vue')['default']
    CreateEditDialog: typeof import('./components/dialogs/CreateEditDialog.vue')['default']
    DeleteConfirmDialog: typeof import('./components/dialogs/DeleteConfirmDialog.vue')['default']
    EarningsGoal: typeof import('./components/charts/EarningsGoal.vue')['default']
    GeneratorField: typeof import('./components/forms/GeneratorField.vue')['default']
    HeartRate: typeof import('./components/charts/HeartRate.vue')['default']
    IconSelector: typeof import('./components/dialogs/IconSelector.vue')['default']
    ProgressCard: typeof import('./components/charts/ProgressCard.vue')['default']
    QueryFilterPanel: typeof import('./components/forms/QueryFilterPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionTable: typeof import('./components/tables/SelectionTable.vue')['default']
    TimelineWithEvent: typeof import('./components/timelines/TimelineWithEvent.vue')['default']
    TreeActivator: typeof import('./components/treeviews/TreeActivator.vue')['default']
    TreeSelector: typeof import('./components/treeviews/TreeSelector.vue')['default']
    Weather: typeof import('./components/charts/Weather.vue')['default']
  }
}
